# -*- coding: utf-8 -*-
"""predict.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k5Nl-4nEX8o74YP9pikG1iHt01uYf0H9
"""

import numpy as np
import tensorflow as tf
import tensorflow.keras as kr

##global parameters
predict_data_size=1
sentece_length=64
embedding_size=64

#random data
predict_data=np.random.random_integers(embedding_maxindex,size=(predict_data_size,sentence_length,embedding_size))

#load model trained by model.py
model=kr.models.load_model('model.h5')
result=model.predict(predict_data)